runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

handlers:

- url: /sw.js
  static_files: sw.js
  upload: sw.js

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json

- url: /smoothie.js
  static_files: smoothie.js
  upload: smoothie.js

- url: /images
  static_dir: images
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: .*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^.*.md|markdown
